# frozen_string_literal: true

require_relative "emitter"

module Aura
  # Generates runnable Ruby from the semantic node list. Torch models become
  # Torch::NN::Module subclasses with a real forward pass (shapes tracked so
  # Linear in-features are computed correctly); LLM models become HTTP client
  # methods; routes become classic-Sinatra handlers.
  class CodeGen
    OPTIMIZERS = { adam: "Adam", adamw: "AdamW", sgd: "SGD", rmsprop: "RMSprop", adagrad: "Adagrad" }.freeze
    LOSSES     = { cross_entropy: "CrossEntropyLoss", mse: "MSELoss", bce: "BCELoss",
                   bce_with_logits: "BCEWithLogitsLoss", nll: "NLLLoss" }.freeze
    SCHEDULERS = { step_lr: "StepLR", exponential_lr: "ExponentialLR",
                   cosine_annealing_lr: "CosineAnnealingLR" }.freeze

    def self.generate(nodes)
      new(nodes).generate
    end

    def initialize(nodes)
      @nodes = nodes
      @e = Emitter.new
      @registry = build_registry
    end

    def generate
      header
      @nodes.each { |node| emit(node) }
      @e.to_s
    end

    private

    def build_registry
      @nodes.select { |n| n[:type] == :model }
            .each_with_object({}) { |m, h| h[m[:name]] = m }
    end

    def llm?
      @registry.values.any? { |m| m[:kind] == :llm }
    end

    def header
      @e.comment "Generated by Aura v#{Aura::VERSION}"
      @e.line %(require "sinatra")
      @e.line %(require "json")
      if llm?
        @e.line %(require "net/http")
        @e.line %(require "uri")
      end
      @e.line %(begin; require "torch"; rescue LoadError; end)
      @e.line %(DEVICE = (defined?(Torch) && Torch.cuda_available?) ? "cuda" : "cpu")
      @e.blank
    end

    def emit(node)
      case node[:type]
      when :environment then emit_environment(node)
      when :dataset     then emit_dataset(node)
      when :model       then emit_model(node)
      when :train       then emit_train(node)
      when :evaluate    then emit_evaluate(node)
      when :route       then emit_route(node)
      when :run_web     then emit_run_web(node)
      end
    end

    # ---- environment ---------------------------------------------------------
    def emit_environment(node)
      pairs = node[:settings].map { |k, v| "#{k}: #{v.inspect}" }.join(", ")
      @e.block("class AuraConfig") do
        @e.line "SETTINGS = { #{pairs} }.freeze"
      end
      @e.blank
    end

    # ---- dataset -------------------------------------------------------------
    def emit_dataset(node)
      @e.comment %(Dataset: #{node[:name]} (#{node[:source]} "#{node[:path]}"))
      @e.line "#{const(node[:name])}_DATASET = { source: #{node[:source].inspect}, " \
              "path: #{node[:path].inspect}, options: #{node[:options].inspect} }.freeze"
      @e.blank
    end

    # ---- models --------------------------------------------------------------
    def emit_model(node)
      case node[:kind]
      when :torch    then emit_torch_model(node)
      when :transfer then emit_transfer_model(node)
      when :llm      then emit_llm_model(node)
      when :text     then emit_text_model(node)
      end
      @e.blank
    end

    def emit_torch_model(node)
      cls = "#{camel(node[:name])}Model"
      init_lines, fwd_lines = plan_layers(node[:layers])

      @e.block("class #{cls} < Torch::NN::Module") do
        @e.block("def initialize") do
          @e.line "super"
          init_lines.each { |l| @e.line l }
        end
        @e.block("def forward(x)") do
          fwd_lines.each { |l| @e.line l }
          @e.line "x"
        end
      end
      accessor(node[:name], "#{cls}.new.to(DEVICE)")
      emit_weight_io(node)
    end

    # Persistence directives declared in the model body (`load weights from` /
    # `save weights to`) become real load calls and a save helper.
    def emit_weight_io(node)
      node[:layers].each do |layer|
        case layer[:type]
        when :load_weights
          @e.line "#{node[:name]}_model.load_state_dict(Torch.load(#{layer[:path].inspect})) if File.exist?(#{layer[:path].inspect})"
        when :save_weights
          @e.line "def #{node[:name]}_save_weights; Torch.save(#{node[:name]}_model.state_dict, #{layer[:path].inspect}); end"
        end
      end
    end

    # Walk the layers once, tracking the running tensor shape so Conv2d
    # in-channels and Linear in-features come out right. Returns [init, forward].
    def plan_layers(layers)
      init = []
      fwd  = []
      spatial = false
      channels = h = w = nil
      flat = nil
      counts = Hash.new(0)

      if (input = layers.find { |l| l[:type] == :input })
        dims = input[:shape]
        if dims.length == 3
          h, w, channels = dims # Aura uses (H, W, C); Torch is channels-first
          spatial = true
        else
          flat = dims.empty? ? nil : dims.reduce(:*)
        end
      end

      flatten = lambda do
        if spatial
          flat = channels * h * w
          spatial = false
          fwd << "x = x.view(x.size(0), -1)"
        end
      end

      layers.each do |layer|
        case layer[:type]
        when :conv2d
          iv = "@conv#{counts[:conv] += 1}"
          pad = (layer[:kernel] - 1) / 2
          init << "#{iv} = Torch::NN::Conv2d.new(#{channels}, #{layer[:filters]}, #{layer[:kernel]}, padding: #{pad})"
          fwd  << "x = Torch::NN::F.relu(#{iv}.call(x))"
          channels = layer[:filters]
        when :maxpool2d
          iv = "@pool#{counts[:pool] += 1}"
          init << "#{iv} = Torch::NN::MaxPool2d.new(#{layer[:size]})"
          fwd  << "x = #{iv}.call(x)"
          h = h / layer[:size] if h
          w = w / layer[:size] if w
        when :batchnorm
          iv = "@bn#{counts[:bn] += 1}"
          init << if spatial
                    "#{iv} = Torch::NN::BatchNorm2d.new(#{channels})"
                  else
                    "#{iv} = Torch::NN::BatchNorm1d.new(#{flat})"
                  end
          fwd << "x = #{iv}.call(x)"
        when :flatten
          flatten.call
        when :dropout
          iv = "@drop#{counts[:drop] += 1}"
          init << "#{iv} = Torch::NN::Dropout.new(p: #{layer[:rate]})"
          fwd  << "x = #{iv}.call(x)"
        when :dense
          flatten.call
          iv = "@fc#{counts[:fc] += 1}"
          init << "#{iv} = Torch::NN::Linear.new(#{flat || 1}, #{layer[:units]})"
          fwd  << "x = #{activation_expr("#{iv}.call(x)", layer[:activation])}"
          flat = layer[:units]
        when :output
          flatten.call
          init << "@out = Torch::NN::Linear.new(#{flat || 1}, #{layer[:units]})"
          fwd  << "x = #{activation_expr("@out.call(x)", layer[:activation])}"
          flat = layer[:units]
        end
      end

      [init, fwd]
    end

    def activation_expr(call_expr, activation)
      case activation
      when :softmax        then "Torch::NN::F.softmax(#{call_expr}, dim: 1)"
      when :linear, nil    then call_expr
      else                      "Torch::NN::F.#{activation}(#{call_expr})"
      end
    end

    def emit_transfer_model(node)
      cls = "#{camel(node[:name])}Model"
      @e.block("class #{cls} < Torch::NN::Module") do
        @e.block("def initialize") do
          @e.line "super"
          @e.line "@base = Torchvision::Models.#{node[:base_model]}(pretrained: true)"
        end
        @e.line "def forward(x); @base.call(x); end"
      end
      accessor(node[:name], "#{cls}.new.to(DEVICE)")
    end

    def emit_llm_model(node)
      case node[:provider]
      when :openai then emit_openai(node)
      when :ollama then emit_ollama(node)
      else              emit_openai(node)
      end
    end

    def emit_openai(node)
      @e.block("def #{node[:name]}_predict(prompt)") do
        @e.line %(api_key = ENV["OPENAI_API_KEY"])
        @e.line %(uri = URI("https://api.openai.com/v1/chat/completions"))
        @e.line "http = Net::HTTP.new(uri.host, uri.port)"
        @e.line "http.use_ssl = true"
        @e.line "request = Net::HTTP::Post.new(uri)"
        @e.line %(request["Content-Type"] = "application/json")
        @e.line %(request["Authorization"] = "Bearer #{'#{api_key}'}")
        @e.line "request.body = { model: #{node[:model_id].inspect}, " \
                "messages: [{ role: \"user\", content: prompt }] }.to_json"
        @e.line "response = http.request(request)"
        @e.line %(JSON.parse(response.body).dig("choices", 0, "message", "content"))
      end
    end

    def emit_ollama(node)
      @e.block("def #{node[:name]}_predict(prompt)") do
        @e.line %(uri = URI("http://localhost:11434/api/generate"))
        @e.line "http = Net::HTTP.new(uri.host, uri.port)"
        @e.line "request = Net::HTTP::Post.new(uri)"
        @e.line %(request["Content-Type"] = "application/json")
        @e.line "request.body = { model: #{node[:model_id].inspect}, prompt: prompt, stream: false }.to_json"
        @e.line "response = http.request(request)"
        @e.line %(JSON.parse(response.body)["response"])
      end
    end

    def emit_text_model(node)
      @e.line "def #{node[:name]}_greeting; #{node[:greeting].inspect}; end"
    end

    # ---- training ------------------------------------------------------------
    def emit_train(node)
      cfg = node[:config]
      model = node[:model]
      @e.comment %(Training: #{model} on "#{node[:dataset]}")
      @e.line "#{model}_model.train"
      lr = cfg[:lr] || 0.001
      @e.line "optimizer = Torch::Optim::#{OPTIMIZERS.fetch(cfg[:optimizer], 'Adam')}.new(#{model}_model.parameters, lr: #{lr})"
      @e.line "criterion = Torch::NN::#{LOSSES.fetch(cfg[:loss], 'CrossEntropyLoss')}.new"
      has_scheduler = cfg[:scheduler] && SCHEDULERS.key?(cfg[:scheduler])
      @e.line "scheduler = Torch::Optim::LRScheduler::#{SCHEDULERS[cfg[:scheduler]]}.new(optimizer, step_size: 1)" if has_scheduler
      @e.block("#{cfg[:epochs] || 1}.times do |epoch|") do
        @e.comment %(Iterate the "#{node[:dataset]}" DataLoader and run the standard step:)
        @e.comment "inputs, targets = batch"
        @e.comment "optimizer.zero_grad"
        @e.comment "loss = criterion.call(#{model}_model.call(inputs), targets)"
        @e.comment "loss.backward; optimizer.step"
        @e.line "scheduler.step" if has_scheduler
      end
      @e.blank
    end

    # ---- evaluation ----------------------------------------------------------
    def emit_evaluate(node)
      @e.comment %(Evaluation: #{node[:model]} on "#{node[:dataset]}")
      @e.line "#{node[:model]}_model.eval"
      @e.block("Torch.no_grad do") do
        @e.comment %(Iterate the "#{node[:dataset]}" DataLoader and accumulate metrics.)
      end
      @e.blank
    end

    # ---- routes --------------------------------------------------------------
    def emit_route(node)
      verb = node[:method].downcase
      model = @registry[node[:model]]
      @e.block("#{verb} '#{node[:path]}' do") do
        @e.line "halt 401 unless request.env['HTTP_AUTHORIZATION']" if node[:auth]
        @e.line "content_type :json" if node[:format] == :json || node[:format].nil?
        emit_route_body(model)
      end
      @e.blank
    end

    def emit_route_body(model)
      kind = model && model[:kind]
      case kind
      when :llm
        @e.line "payload = JSON.parse(request.body.read) rescue {}"
        @e.line "result = #{model[:name]}_predict(payload[\"message\"])"
        @e.line "{ response: result }.to_json"
      when :text
        @e.line "{ greeting: #{model[:name]}_greeting }.to_json"
      when :torch, :transfer
        @e.line "payload = JSON.parse(request.body.read) rescue {}"
        @e.line "input = payload[\"input\"]"
        @e.line "result = #{model[:name]}_model.call(Torch.tensor(input))"
        @e.line "{ prediction: result.to_a }.to_json"
      else
        @e.line "{ status: \"ok\" }.to_json"
      end
    end

    # ---- run -----------------------------------------------------------------
    def emit_run_web(node)
      @e.comment "Boot the Sinatra server (classic mode auto-runs at exit)."
      @e.line "set :port, #{node[:port]}"
      @e.line %(set :bind, "0.0.0.0")
    end

    # ---- helpers -------------------------------------------------------------
    # A memoized, top-level accessor so the model is reachable from inside
    # Sinatra route blocks (which run in their own context).
    def accessor(name, expression)
      @e.line "def #{name}_model; $aura_#{name}_model ||= #{expression}; end"
    end

    def camel(name)
      name.to_s.split(/[_\s]+/).map { |p| p.empty? ? p : p[0].upcase + p[1..] }.join
    end

    def const(name)
      name.to_s.gsub(/[^a-zA-Z0-9]/, "_").upcase
    end
  end
end
