# frozen_string_literal: true

require "fileutils"

module Aura
  # Generates production deployment assets next to an .aura file: the
  # transpiled standalone Ruby app, a Dockerfile, and a .dockerignore. Backs
  # the `aura deploy` command.
  module Docker
    module_function

    def build(filename)
      source = File.read(filename)
      ruby_code = Aura.transpile(source)

      dir  = File.dirname(filename)
      base = File.basename(filename, ".aura")
      app_file = File.join(dir, "#{base}.rb")

      File.write(app_file, ruby_code)
      File.write(File.join(dir, "Dockerfile"), dockerfile("#{base}.rb"))
      File.write(File.join(dir, ".dockerignore"), dockerignore)

      puts "Generated deployment assets:"
      puts "   - #{app_file}"
      puts "   - #{File.join(dir, 'Dockerfile')}"
      puts "   - #{File.join(dir, '.dockerignore')}"
      puts "   Build with: docker build -t #{base} #{dir.empty? ? '.' : dir}"
    end

    def dockerfile(app_file)
      <<~DOCKER
        # Generated by Aura v#{Aura::VERSION}
        FROM ruby:3.3-slim

        WORKDIR /app

        RUN apt-get update -qq \\
          && apt-get install -y --no-install-recommends build-essential \\
          && rm -rf /var/lib/apt/lists/*

        RUN gem install sinatra puma json

        COPY . .

        ENV RACK_ENV=production
        EXPOSE 3000

        CMD ["ruby", "#{app_file}"]
      DOCKER
    end

    def dockerignore
      <<~IGNORE
        .git
        *.aura
        models/*.pth
        data/
        tmp/
        *.log
      IGNORE
    end
  end
end
